import { chromium } from 'playwright';
const BASE = 'http://127.0.0.1:4321';
const OUT = '_shots';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1 });
const page = await ctx.newPage();
await page.goto(BASE + '/', { waitUntil: 'load', timeout: 30000 });
await page.waitForTimeout(500);
await page.screenshot({ path: `${OUT}/chat-collapsed.png`, fullPage: false });
console.log('collapsed');
await page.click('#chat-toggle');
await page.waitForTimeout(400);
await page.screenshot({ path: `${OUT}/chat-open.png`, fullPage: false });
console.log('open');
await page.click('#chat-toggle');
await page.waitForTimeout(400);
const stillVisible = await page.isVisible('#chat-panel');
await page.screenshot({ path: `${OUT}/chat-closed.png`, fullPage: false });
console.log('closed; panel visible after close =', stillVisible);
await browser.close();
