import { chromium } from 'playwright';
const BASE='http://127.0.0.1:4321';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1});
const p=await ctx.newPage();
await p.goto(BASE+'/',{waitUntil:'load',timeout:30000});
await p.waitForTimeout(800);
const loc=p.locator('.trust-bar').first();
await loc.scrollIntoViewIfNeeded();
await p.waitForTimeout(200);
await loc.screenshot({path:'_shots/trustbar.png'});
console.log('done');
await b.close();
